@@startuml
class Game {
    int ATTEMPTS_NUMBER=10
    Attempt secretKey
    Player player
    Board board

    String inputCombination()
    void play()
    boolean isSecretKey(Attempt attempt)
}

enum Colors {
    BLUE "b"
    GREEN "g"
    CYAN "c"
    RED "r"
    PURPLE "p"
    ORANGE "o"
    VIOLET "v"
    YELLOW "y"
    
    String nickname
    char getNickname()
    void setNickname(char nickname)
    String printAllColors()
    boolean contains(String inputs)
    HashMap<char, Colors> getMap()
}

class Attempt { 
    Colors[] colors
    void setColors(String inputs)
    Attempt getRandomAttempt()
    String toString()
}

Class Peg {
    int[] pegs length=2
    void setPegs(int[] pegs)
    String toString()
}

class Player {
    int COMBINATION_NUMBER=4
    ArrayList<Attempt> attempts
    ArrayList<Peg> pegs
    void readAttempt(String inputs)
}

class Board {
    void print(Player player, Attempt secretKey,boolean displaySecretKey)
}

class ManagementIO {
}

Game --* Attempt
Game --* Player
Game --* Board
Player "1" --* "ATTEMPTS_NUMBER" Attempt
Player "1" --* "ATTEMPTS_NUMBER" Peg
Attempt "1" --* "COMBINATION_NUMBER" Colors 
Board ..> Player
Board ..> Attempt
Board ..> Peg
Game ..> ManagementIO
Board ..> ManagementIO
@@enduml
